stud1=int(input("Введіть кількість учнів в першій группі "))
stud2=int(input("Введіть кількість учнів в другій группі "))
stud3=int(input("Введіть кількість учнів в третій группі "))
stud=int(stud1+stud2+stud3)
table=int((stud/2)+(stud%2))
print("Кількість потрібних столів дорівнює", (str)(table))
input("")
