number=int(input("Введіть ціле число "))
nex=int(number+1)
prev=int(number-1)
print("The next number for the number",(str)(number),"is",(str)(nex),"\nThe previous number for the number",(str)(number),"is",(str)(prev))
input("")
