print('Apple sharing')
students = int(input('Students:'))
apples = int(input('Apples:'))
print('Amount of apples each student get:',apples // students)
print('Amount of apples left in basket:',apples % students)
input()
