print("This program shows adjacent numbers")
number=int(input("Enter the number:"))
print("The next number for the number", number, "is", number+1)
print("The previous number for the number", number, "is", number-1)
input("\n\nPress Enter to exit the program.")
