print("This program calculates the amount a+b+c")
a=float(input("Enter a value for the variable a="))
b=float(input("Enter a value for the variable b="))
c=float(input("Enter a value for the variable c="))
print("a+b+c=", a+b+c)
input("\n\nPress Enter to exit the program.")
