print("Введіть три числа для розрахунка їх суми")
a=float(input("Введіть перше число "))
b=float(input("Введіть друге число "))
c=float(input("Введіть третэ число "))
sum=float(a+b+c)
print("Сума чисел дорівнює ",(str)(sum))
input()
